web/router.ex
defmodule Storyvue.Router do
  use Storyvue.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Storyvue do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/registration", RegistrationController, only: [:new, :create]

    resources "/stories", StoryController do
      resources "/sections", SectionController do
        resources "/moments", MomentController
      end
      resources "/characters", CharacterController do
        resources "/tags", CharTagController, only: [:index, :new, :create, :edit, :update, :delete]
      end
      resources "/tags", StoryTagController, only: [:index, :new, :create, :edit, :update, :delete]
      resources "/notes", NoteController, only: [:index, :new, :create]
    end

    get "/login",  SessionController, :new
    post "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

    get "/dashboard", DashboardController, :index

    get "/account", AccountController, :index
    get "/account/:id/edit", AccountController, :edit
    put "/account/:id", AccountController, :update
    delete "/account/:id", AccountController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Storyvue do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Storyvue.LayoutView do
  use Storyvue.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Storyvue | Organize your next story</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link to: page_path(@conn, :index), class: "navbar-brand" do %>
            <img src="/images/new-logo.png" alt="StoryVue Logo">
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
              <button type="submit" class="btn btn-secondary"><i class="material-icons">search</i></button>
            </div>

          </form>
          <ul class="nav navbar-nav navbar-right">
            <%= if logged_in?(@conn) do %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user(@conn).email %>&nbsp; <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link to: dashboard_path(@conn, :index) do %>
                  <i class="material-icons md-18">dashboard</i>&nbsp; Dashboard <% end %>
                </li>
                <li><%= link to: story_path(@conn, :index) do %>
                  <i class="material-icons md-18">library_books</i>&nbsp; Stories <% end %>
                </li>
                <li><%= link to: account_path(@conn, :index) do %>
                  <i class="material-icons md-18">account_box</i>&nbsp; Manage Account <% end %>
                </li>
                <li><%= link to: session_path(@conn, :delete), method: :delete do %>
                  <i class="material-icons md-18">exit_to_app</i>&nbsp; Logout <% end %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link "Login", to: "/login" %></li>
              <li><%= link "Register", to: registration_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <section class="flash-messages">
      <%= if get_flash(@conn, :info) do %>
        <div class="alert alert-info" role="alert">
          <div class="container-fluid">
            <h4><i class="material-icons">check</i> <%= get_flash(@conn, :info) %></h4>
          </div>
        </div>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <div class="alert alert-danger" role="alert">
          <div class="container">
            <h4><i class="material-icons">warning</i> <%= get_flash(@conn, :error) %></h4>
          </div>
        </div>
      <% end %>
    </section>

    <section role="main">
      <%= render @view_module, @view_template, assigns %>
    </section>

    <footer>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            &copy; 2018, StoryVue
          </div>
        </div>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.8.6/showdown.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>