web/router.ex
defmodule Storyvue.Router do
  use Storyvue.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Storyvue do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/registration", RegistrationController, only: [:new, :create]

    resources "/stories", StoryController do
      resources "/sections", SectionController do
        resources "/moments", MomentController
      end
      resources "/characters", CharacterController do
        resources "/tags", CharTagController, only: [:index, :new, :create, :edit, :update, :delete]
      end
      resources "/tags", StoryTagController, only: [:index, :new, :create, :edit, :update, :delete]
      resources "/notes", NoteController, only: [:index, :new, :create]
    end

    get "/login",  SessionController, :new
    post "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

    get "/dashboard", DashboardController, :index

    get "/account", AccountController, :index
    get "/account/:id/edit", AccountController, :edit
    put "/account/:id", AccountController, :update
    delete "/account/:id", AccountController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Storyvue do
  #   pipe_through :api
  # end
end

web/models/character.ex
defmodule Storyvue.Character do
  use Storyvue.Web, :model
  alias Storyvue.CharTag

  schema "characters" do
    field :char_name, :string
    field :char_image, :string
    field :char_date_of_birth, :date
    field :char_place_of_birth, :string
    field :char_education, :string
    field :char_school, :string
    field :char_occupation, :string
    field :char_description, :string
    field :char_desire, :string
    field :story_id, :integer
    has_many :char_tags, CharTag, foreign_key: :char_id

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:char_name, :char_image, :char_date_of_birth, :char_place_of_birth, :char_education, :char_school, :char_occupation, :char_description, :char_desire, :story_id])
    |> validate_required([:char_name, :story_id])
  end
end

web/controllers/character_controller.ex
defmodule Storyvue.CharacterController do
  use Storyvue.Web, :controller
  use Timex
  alias Storyvue.Character
  alias Storyvue.CharTag
  alias Storyvue.Story

  def index(conn, %{"story_id" => story_id}) do
    character_query = from c in Character,
      where: c.story_id == ^story_id,
      preload: [:char_tags]
    characters = Repo.all(character_query)
    story = Repo.get(Story, story_id)
    render conn, "index.html", characters: characters, story_id: story_id, story: story
  end

  def new(conn, %{"story_id" => story_id}) do
    changeset = Character.changeset(%Character{}, %{})
    render conn, "new.html", changeset: changeset, story_id: story_id
  end

  def create(conn, %{"character" => character, "story_id" => story_id}) do
    changeset = Character.changeset(%Character{}, character)

    case Repo.insert(changeset) do
      {:ok, _character} ->
        conn
        |> put_flash(:info, "Your new character was successfully created")
        |> redirect(to: story_path(conn, :show, story_id))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def show(conn, %{"id" => char_id, "story_id" => story_id}) do
    character = Repo.get(Character, char_id)

    character_age = Timex.diff(Timex.today, character.char_date_of_birth, :days) |> div(365)

    IO.inspect(character)
    render conn, "show.html", character: character, story_id: story_id, char_age: character_age
  end

  def edit(conn, %{"id" => character_id, "story_id" => story_id}) do
    character = Repo.get(Character, character_id)
    changeset = Character.changeset(character)

    render conn, "edit.html", changeset: changeset, character: character, story_id: story_id
  end

  def update(conn, %{"id" => char_id, "character" => character, "story_id" => story_id}) do
    old_character = Repo.get(Character, char_id)
    changeset = Character.changeset(old_character, character)

    case Repo.update(changeset) do
      {:ok, _character} ->
        conn
        |> put_flash(:info, "Your character was successfully updated")
        |> redirect(to: story_character_path(conn, :show, story_id, char_id))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, character: old_character
    end
  end

  def delete(conn, %{"id" => char_id, "story_id" => story_id}) do
    Repo.get!(Character, char_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Your character was successfully deleted")
    |> redirect(to: story_character_path(conn, :index, story_id))
  end
end

web/views/character_view.ex
defmodule Storyvue.CharacterView do
  use Storyvue.Web, :view
end

web/templates/character/edit.html.eex
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Edit <%= @character.char_name %></h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container">
    <%= link to: story_character_path(@conn, :show, @story_id, @character.id) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Character
    <% end %>
  </div>
</div>

<main class="container">
  <div class="fixed-button header-button">
    <%= link to: story_character_path(@conn, :delete, @story_id, @character.id), method: :delete, class: "btn btn-danger btn-round", title: "Delete this character" do %>
      <i class="material-icons">delete</i>
    <% end %>
  </div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @changeset, story_character_path(@conn, :update, @story_id, @character.id), fn f -> %>
        <div class="form-group form-group-lg">
          <label for="character_title">Name:</label>
          <%= text_input f, :char_name, placeholder: "What is this characters name?", class: "form-control" %>
          <%= error_tag f, :char_name %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Upload an Image of your Character:</label>
          <%= url_input f, :char_image, placeholder: "Add a link to an image of this character", class: "form-control" %>
          <%= error_tag f, :char_image %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Date of Birth:</label>
          <%= date_input f, :char_date_of_birth, placeholder: "When whas this character born?", class: "form-control" %>
          <%= error_tag f, :char_date_of_birth %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Place of Birth:</label>
          <%= text_input f, :char_place_of_birth, placeholder: "Where whas this character born?", class: "form-control" %>
          <%= error_tag f, :char_place_of_birth %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Education:</label>
          <%= select f, :char_education, ["None": "None", "High School": "High School", "Associates Degree": "Associates Degree", "Bachelors Degree": "Bachelors College", "Masters Degree": "Masters Degree", "Phd": "Phd"], class: "form-control" %>
          <%= error_tag f, :char_education %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">School Attended:</label>
          <%= text_input f, :char_school, placeholder: "Which school did this character attend?", class: "form-control" %>
          <%= error_tag f, :char_school %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Occupation:</label>
          <%= text_input f, :char_occupation, placeholder: "What occupation does this character have?", class: "form-control" %>
          <%= error_tag f, :char_occupation %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_desire">Goals:</label>
          <%= textarea f, :char_desire, placeholder: "What are your characters desires? What are they trying to acheive/accomplish?", class: "form-control" %>
          <%= error_tag f, :char_desire %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_description">Description:</label>
          <%= textarea f, :char_description, placeholder: "Give a brief description of your new character. This can include appearance, traits, etc.", class: "form-control" %>
          <%= error_tag f, :char_description %>
        </div>

        <div class="form-group form-group-lg">
          <%= submit class: "btn btn-lg btn-secondary" do %>
            Update character
          <% end %>
          <%= link "Cancel", to: story_character_path(@conn, :show, @story_id, @character.id), class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

web/templates/character/index.html.eex
<div class="jumbotron">
  <div class="container-fluid">
    <h1 class="text-center">Characters</h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container-fluid">
    <%= link to: story_path(@conn, :show, @story_id) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Story
    <% end %>
  </div>
</div>

<main class="container-fluid">
  <div class="fixed-button header-button">
    <%= link to: story_character_path(@conn, :new, @story_id), class: "btn btn-secondary btn-round", title: "Add a new character" do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
</main>

<div class="container-fluid the-content with-sidebar">
  <div class="row character-grid">
    <div class="col-md-2">
      <div class="sidebar">
        <ul>
          <li>
            <%= link "Story", to: story_path(@conn, :show, @story_id) %>
            <%= link "Characters", to: story_character_path(@conn, :index, @story_id), class: "active-sidebar-nav" %>
            <a href="#">Timeline</a>
            <a href="#">Sections</a>
            <a href="#">Moments</a>
            <%= link "Notes", to: story_note_path(@conn, :index, @story_id) %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-9">
      <%= for character <- @characters do %>
        <div class="col-md-char">
          <div href="#" class="panel panel-default panel-character panel-truncate">
            <div class="panel-heading">
              <h4 class="text-center"><%= character.char_name %></h4>
              <button type="button" class="kebab" data-toggle="panel-heading-menu">
                <i class="material-icons">more_vert</i>
              </button>
              <div class="panel-heading-menu hidden">
                <ul>
                  <li>
                    <%= link to: story_character_char_tag_path(@conn, :index, @story_id, character.id) do %>
                      <i class="material-icons md-18">label</i> &nbsp;Tags
                    <% end %>
                    <%= link to: story_character_path(@conn, :edit, @story_id, character.id ) do %>
                      <i class="material-icons md-18">settings</i> &nbsp;Settings
                    <% end %>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="panel-body">
              <%= if character.char_image do %>
                <div class="panel-body-image" style="background-image:url('<%= character.char_image %>');"></div>
              <% else %>
                <div class="panel-body-image" style="background-image:url('/images/user-image2.jpg');"></div>
              <% end %>
              <p><%= character.char_description %></p>
              <div class="panel-body-badges">
                <%= for char_tag <- character.char_tags do %>
                  <span class="badge" style="background-color: <%= char_tag.tag_color %>;"><%= char_tag.tag_title %></span>
                <% end %>
              </div>
            </div>
            <div class="panel-footer">
              <%= link to: story_character_path(@conn, :show, @story_id, character.id), class: "btn btn-lg btn-secondary" do %>
                View Character <i class="material-icons">arrow_right</i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

web/templates/character/new.html.eex
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Create a New Character</h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container">
    <%= link to: story_character_path(@conn, :index, @story_id) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Characters
    <% end %>
  </div>
</div>

<main class="container">
  <div class="fixed-button header-button">
    <div style="height: 70px;">
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @changeset, story_character_path(@conn, :create, @story_id), [multipart: true], fn f -> %>
        <div class="form-group form-group-lg">
          <label for="character_title">Name:</label>
          <%= text_input f, :char_name, placeholder: "What is this characters name?", class: "form-control" %>
          <%= error_tag f, :char_name %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Upload an Image of your Character:</label>
          <%= url_input f, :char_image, placeholder: "Add a link to an image of this character", class: "form-control" %>
          <%= error_tag f, :char_image %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Date of Birth:</label>
          <%= date_input f, :char_date_of_birth, placeholder: "When whas this character born?", class: "form-control" %>
          <%= error_tag f, :char_date_of_birth %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Place of Birth:</label>
          <%= text_input f, :char_place_of_birth, placeholder: "Where whas this character born?", class: "form-control" %>
          <%= error_tag f, :char_place_of_birth %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Education:</label>
          <%= select f, :char_education, ["None": "None", "High School": "High School", "Associates Degree": "Associates Degree", "Bachelors Degree": "Bachelors Degree", "Masters Degree": "Masters Degree", "Phd": "Phd"], class: "form-control" %>
          <%= error_tag f, :char_education %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">School Attended:</label>
          <%= text_input f, :char_school, placeholder: "Which school did this character attend?", class: "form-control" %>
          <%= error_tag f, :char_school %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_title">Occupation:</label>
          <%= text_input f, :char_occupation, placeholder: "What occupation does this character have?", class: "form-control" %>
          <%= error_tag f, :char_occupation %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_desire">Goals:</label>
          <%= textarea f, :char_desire, placeholder: "What are your characters desires? What are they trying to acheive/accomplish?", class: "form-control" %>
          <%= error_tag f, :char_desire %>
        </div>

        <div class="form-group form-group-lg">
          <label for="character_description">Description:</label>
          <%= textarea f, :char_description, placeholder: "Give a brief description of your new character. This can include appearance, traits, etc.", class: "form-control" %>
          <%= error_tag f, :char_description %>
        </div>

        <%= hidden_input f, :story_id, value: @story_id %>

        <div class="form-group form-group-lg">
          <%= submit class: "btn btn-lg btn-secondary" do %>
            Create Character
          <% end %>
          <%= link "Cancel", to: story_character_path(@conn, :index, @story_id), class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

web/templates/character/show.html.eex
<div class="jumbotron">
  <div class="container-fluid">
    <h1 class="text-center"><%= @character.char_name %></h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container-fluid">
    <%= link to: story_character_path(@conn, :index, @story_id) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Characters
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <div class="fixed-button header-button">
    <%= link to: story_character_path(@conn, :edit, @story_id, @character.id), class: "btn btn-secondary btn-round", title: "Edit this character" do %>
      <i class="material-icons">edit</i>
    <% end %>
  </div>
</div>

<div class="container-fluid with-sidebar">
  <div class="row">
    <div class="col-md-2">
      <div class="sidebar">
        <ul>
          <li>
            <%= link "Story", to: story_path(@conn, :show, @story_id) %>
            <%= link "Characters", to: story_character_path(@conn, :index, @story_id), class: "active-sidebar-nav" %>
            <a href="#">Timeline</a>
            <a href="#">Sections</a>
            <a href="#">Moments</a>
            <%= link "Notes", to: story_note_path(@conn, :index, @story_id) %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-3 col-md-offset-1">
      <div class="panel panel-default character-panel">
        <%= if @character.char_image do %>
          <div class="character-image" style="background-image:url('<%= @character.char_image %>');"></div>
        <% else %>
          <div class="character-image" style="background-image:url('/images/user-image2.jpg');"></div>
        <% end %>
        <h3>Description</h3>
        <h5>This is the description of your character.</h5>
        <p><%= @character.char_description %></p>
        <%= if @character.char_place_of_birth do %>
          <p>Born: <%= @character.char_place_of_birth %></p>
        <% end %>
        <%= if @character.char_date_of_birth do %>
          <p>Age: <%= @char_age %></p>
        <% end %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="panel panel-default character-panel">
        <%= if @character.char_education do %>
          <h3>Education</h3>
          <h5>Character's education information.</h5>
          <p><%= @character.char_education %> from <%= @character.char_school %></p>
        <% end %>
      </div>
      <div class="panel panel-default character-panel">
        <%= if @character.char_occupation do %>
          <h3>Occupation</h3>
          <h5>Character's occupation information.</h5>
          <p><%= @character.char_occupation %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>