web/router.ex
defmodule Storyvue.Router do
  use Storyvue.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Storyvue do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/registration", RegistrationController, only: [:new, :create]

    resources "/stories", StoryController do
      resources "/sections", SectionController do
        resources "/moments", MomentController
      end
      resources "/characters", CharacterController do
        resources "/tags", CharTagController, only: [:index, :new, :create, :edit, :update, :delete]
      end
      resources "/tags", StoryTagController, only: [:index, :new, :create, :edit, :update, :delete]
      resources "/notes", NoteController, only: [:index, :new, :create]
    end

    get "/login",  SessionController, :new
    post "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

    get "/dashboard", DashboardController, :index

    get "/account", AccountController, :index
    get "/account/:id/edit", AccountController, :edit
    put "/account/:id", AccountController, :update
    delete "/account/:id", AccountController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Storyvue do
  #   pipe_through :api
  # end
end

web/models/story.ex
defmodule Storyvue.Story do
  use Storyvue.Web, :model
  alias Storyvue.Character
  alias Storyvue.StoryTag
  alias Storyvue.Section

  schema "stories" do
    field :title, :string
    field :description, :string
    field :user_id, :integer
    has_many :sections, Section
    has_many :characters, Character
    has_many :story_tags, StoryTag

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :description, :user_id])
    |> validate_required([:title, :description, :user_id])
  end
end

web/controllers/story_controller.ex
defmodule Storyvue.StoryController do
  use Storyvue.Web, :controller
  alias Storyvue.Story
  alias Storyvue.CharTag
  alias Storyvue.StoryTag

  def index(conn, _params) do
    current_user_id = Plug.Conn.get_session(conn, :current_user)
    story_query = from s in Story,
      where: s.user_id == ^current_user_id,
      preload: [:story_tags]
    stories = Repo.all(story_query)
    render conn, "index.html", stories: stories
  end

  def new(conn, _params) do
    changeset = Story.changeset(%Story{}, %{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"story" => story}) do
    changeset = Story.changeset(%Story{}, story)

    case Repo.insert(changeset) do
      {:ok, _story} ->
        conn
        |> put_flash(:info, "Your new story was successfully created")
        |> redirect(to: story_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def show(conn, %{"id" => story_id}) do
    story = Repo.get(Story, story_id) |> Repo.preload([:sections, [{:characters, :char_tags}]])

    render conn, "show.html", story: story
  end

  def edit(conn, %{"id" => story_id}) do
    story = Repo.get(Story, story_id)
    changeset = Story.changeset(story)

    render conn, "edit.html", changeset: changeset, story: story
  end

  def update(conn, %{"id" => story_id, "story" => story}) do
    old_story = Repo.get(Story, story_id)
    changeset = Story.changeset(old_story, story)

    case Repo.update(changeset) do
      {:ok, _payment} ->
        conn
        |> put_flash(:info, "Your story was successfully updated")
        |> redirect(to: story_path(conn, :show, story_id))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, story: old_story
    end
  end

  def delete(conn, %{"id" => story_id}) do
    character_query = from c in Storyvue.Character, where: c.story_id == ^story_id
    characters = Repo.all(character_query)
      for character <- characters do
        Repo.get!(Storyvue.Character, character.id)
        |> Repo.delete!
      end
    Repo.get!(Story, story_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Your story was successfully deleted")
    |> redirect(to: story_path(conn, :index))
  end
end

web/views/story_view.ex
defmodule Storyvue.StoryView do
  use Storyvue.Web, :view
end

web/templates/story/edit.html.eex
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Edit <%= @story.title %></h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container">
    <%= link to: story_path(@conn, :show, @story.id) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Story
    <% end %>
  </div>
</div>

<main class="container">
  <div class="fixed-button header-button">
    <%= link to: story_path(@conn, :delete, @story.id), method: :delete, class: "btn btn-danger btn-round", title: "Delete this story" do %>
      <i class="material-icons">delete</i>
    <% end %>
  </div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @changeset, story_path(@conn, :update, @story), fn f -> %>
        <div class="form-group form-group-lg">
          <label for="story_title">Title:</label>
          <%= text_input f, :title, placeholder: "Give your new story a title", class: "form-control" %>
          <%= error_tag f, :title %>
        </div>

        <div class="form-group form-group-lg">
          <label for="story_description">Description:</label>
          <%= textarea f, :description, placeholder: "Give a brief synopsis of your new story. You can always change this later!", class: "form-control" %>
          <%= error_tag f, :description %>
        </div>

        <%= hidden_input f, :user_id, value: current_user(@conn).id %>

        <div class="form-group form-group-lg">
          <%= submit class: "btn btn-lg btn-secondary" do %>
            Update Story
          <% end %>
          <%= link "Cancel", to: story_path(@conn, :show, @story), class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

web/templates/story/index.html.eex
<div class="jumbotron">
  <div class="container-fluid">
    <h1 class="text-center">Your Stories</h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container-fluid">
    <%= link to: dashboard_path(@conn, :index) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Dashboard
    <% end %>
  </div>

</div>

<div class="container-fluid">
  <div class="fixed-button header-button">
    <%= link to: story_path(@conn, :new), class: "btn btn-secondary btn-round", title: "Create a new story" do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
</div>

<div class="container the-content" style="padding-bottom: 170px;">
  <div class="row">
    <%= for story <- @stories do %>
      <div class="col-md-4">
        <div href="#" class="panel panel-default panel-truncate">
          <div class="panel-heading">
            <h4 class="text-center"><%= story.title %></h4>
            <button type="button" class="kebab" data-toggle="panel-heading-menu">
              <i class="material-icons">more_vert</i>
            </button>
            <div class="panel-heading-menu hidden">
              <ul>
                <li>
                  <%= link to: story_story_tag_path(@conn, :index, story.id) do %>
                    <i class="material-icons md-18">label</i> &nbsp;Tags
                  <% end %>
                  <%= link to: story_path(@conn, :edit, story.id) do %>
                    <i class="material-icons md-18">settings</i> &nbsp;Settings
                  <% end %>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="panel-body">
            <p class="list-group-item-text"><%= story.description %></p>
          </div>
          <div class="panel-body-badges">
            <%= for story_tag <- story.story_tags do %>
              <span class="badge" style="background-color: <%= story_tag.tag_color %>;"><%= story_tag.tag_title %></span>
            <% end %>
          </div>
          <div class="panel-footer">
            <%= link to: story_path(@conn, :show, story), class: "btn btn-lg btn-secondary" do %>
              View Story <i class="material-icons">arrow_right</i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

web/templates/story/new.html.eex
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Create a New Story</h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container">
    <%= link to: story_path(@conn, :index) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Stories
    <% end %>
  </div>
</div>

<main class="container">
  <div class="fixed-button header-button">
    <div style="height: 70px;">
    </div>
  </div>
</div>

<main class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @changeset, story_path(@conn, :create), fn f -> %>
        <div class="form-group form-group-lg">
          <label for="story_title">Title:</label>
          <%= text_input f, :title, placeholder: "Give your new story a title", class: "form-control" %>
          <%= error_tag f, :title %>
        </div>

        <div class="form-group form-group-lg">
          <label for="story_description">Description:</label>
          <%= textarea f, :description, placeholder: "Give a brief synopsis of your new story. You can always change this later!", class: "form-control" %>
          <%= error_tag f, :description %>
        </div>

        <%= hidden_input f, :user_id, value: current_user(@conn).id %>

        <div class="form-group form-group-lg">
          <%= submit class: "btn btn-lg btn-secondary" do %>
            Create Story
          <% end %>
          <%= link "Cancel", to: story_path(@conn, :index), class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</main>

web/templates/story/show.html.eex
<div class="jumbotron">
  <div class="container-fluid">
    <h1 class="text-center"><%= @story.title %></h1>
  </div>
</div>

<div class="bread-crumbs">
  <div class="container-fluid">
    <%= link to: story_path(@conn, :index) do %>
      <i class="material-icons md-18">arrow_back_ios</i> Back to Stories
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <div class="fixed-button header-button">
    <%= link to: story_path(@conn, :edit, @story.id), class: "btn btn-secondary btn-round", title: "Edit this story"  do %>
      <i class="material-icons">edit</i>
    <% end %>
  </div>
</div>

<div class="container-fluid with-sidebar">
  <div class="row">
    <div class="col-md-2">
      <div class="sidebar">
        <ul>
          <li>
            <%= link "Story", to: story_path(@conn, :show, @story.id), class: "active-sidebar-nav" %>
            <%= link "Characters", to: story_character_path(@conn, :index, @story.id) %>
            <a href="#">Timeline</a>
            <a href="#">Sections</a>
            <a href="#">Moments</a>
            <%= link "Notes", to: story_note_path(@conn, :index, @story.id) %>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-md-9">
      <div class="panel panel-default story-panel">
        <h3>Theme</h3>
        <h5>These are your theme and mood panels.</h5>
        
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="panel panel-default story-panel">
            <h3>Description</h3>
            <h5>This is the short description of your story.</h5>
            <p><%= @story.description %></p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default story-panel">
            <h3>Characters</h3>
            <h5>The characters that appear in your story.</h5>
            <%= for character <- @story.characters do %>
              <div class="media-small">
                <%= link to: story_character_path(@conn, :show, @story.id, character.id) do %>
                  <%= if character.char_image do %>
                    <div data-toggle="tooltip" title="<%= character.char_name %>" class="media-small-img" style="background-image:url('<%= character.char_image %>');"></div>
                  <% else %>
                    <div data-toggle="tooltip" title="<%= character.char_name %>" class="media-small-img" style="background-image:url('/images/user-image2.jpg');"></div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
            <br />
            <%= link "View All", to: story_character_path(@conn, :index, @story.id), class: "btn btn-secondary btn-md" %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default story-panel">
            <h3>Timeline</h3>
            <div class="timeline">
              <%= for section <- @story.sections do %>
                <div class="panel panel-default story-panel">
                  <h4><%= section.title %></h4>
                </div>
              <% end %>
              <%= link "Create a Section", to: story_section_path(@conn, :new, @story.id), class: "btn btn-secondary btn-md" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>